// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Warehourse.ProductPlacement.Infrastructure.DbContexts;

#nullable disable

namespace Warehourse.ProductPlacement.Infrastructure.Migrations
{
    [DbContext(typeof(ProductReadDbContext))]
    [Migration("20250504195703_InitialК")]
    partial class InitialК
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("WarehouseManagement")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Warehourse.ProductPlacement.Contracts.Dtos.PendingProductDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.ComplexProperty<Dictionary<string, object>>("Size", "Warehourse.ProductPlacement.Contracts.Dtos.PendingProductDto.Size#SizeDto", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Height")
                                .HasColumnType("double precision")
                                .HasColumnName("size_height");

                            b1.Property<double>("Length")
                                .HasColumnType("double precision")
                                .HasColumnName("size_length");

                            b1.Property<double>("Width")
                                .HasColumnType("double precision")
                                .HasColumnName("size_width");
                        });

                    b.HasKey("Id")
                        .HasName("pk_pending_products");

                    b.ToTable("pending_products", "WarehouseManagement");
                });

            modelBuilder.Entity("Warehourse.ProductPlacement.Contracts.Dtos.ProductDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.ComplexProperty<Dictionary<string, object>>("Size", "Warehourse.ProductPlacement.Contracts.Dtos.ProductDto.Size#SizeDto", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Height")
                                .HasColumnType("double precision")
                                .HasColumnName("size_height");

                            b1.Property<double>("Length")
                                .HasColumnType("double precision")
                                .HasColumnName("size_length");

                            b1.Property<double>("Width")
                                .HasColumnType("double precision")
                                .HasColumnName("size_width");
                        });

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.ToTable("products", "WarehouseManagement");
                });

            modelBuilder.Entity("Warehourse.ProductPlacement.Contracts.Dtos.ProductStorageDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.ComplexProperty<Dictionary<string, object>>("ShelfPosition", "Warehourse.ProductPlacement.Contracts.Dtos.ProductStorageDto.ShelfPosition#ShelfPositionDto", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("SectionRowNumber")
                                .HasColumnType("integer")
                                .HasColumnName("shelf_position_section_row_number");

                            b1.Property<int>("ShelfColumnNumber")
                                .HasColumnType("integer")
                                .HasColumnName("shelf_position_shelf_column_number");

                            b1.Property<int>("ShelfRowNumber")
                                .HasColumnType("integer")
                                .HasColumnName("shelf_position_shelf_row_number");
                        });

                    b.HasKey("Id")
                        .HasName("pk_product_storages");

                    b.ToTable("product_storages", "WarehouseManagement");
                });
#pragma warning restore 612, 618
        }
    }
}
